// Package api 提供 synkord-core 业务路由。
//
// 依赖关系在 MVP 阶段只读：依赖关系由 Swagger / OpenAPI / Postman 导入
// 自动解析 $ref 生成，不提供手动新增、编辑、删除的 REST 端点。
package api

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/synkord/core/database"
	"github.com/synkord/core/services"
)

func RegisterTeamDependencyRoutes(r *gin.RouterGroup) {
	d := r.Group("/teams/:team_id/projects/:project_id/dependencies")
	{
		d.GET("/graph", func(c *gin.Context) {
			teamID := c.Param("team_id")
			projectID := c.Param("project_id")
			if _, err := services.GetTeamForUser(database.DB, teamID, c.GetString("user_id")); err != nil {
				c.JSON(http.StatusNotFound, gin.H{"detail": "Team not found"})
				return
			}
			if !projectBelongsToTeam(projectID, teamID) {
				c.JSON(http.StatusNotFound, gin.H{"detail": "Project not found"})
				return
			}
			graph, err := services.GetProjectDependencyGraph(database.DB, teamID, projectID)
			if err != nil {
				c.JSON(http.StatusInternalServerError, gin.H{"detail": err.Error()})
				return
			}
			c.JSON(http.StatusOK, graph)
		})

		d.GET("", func(c *gin.Context) {
			teamID := c.Param("team_id")
			projectID := c.Param("project_id")
			if _, err := services.GetTeamForUser(database.DB, teamID, c.GetString("user_id")); err != nil {
				c.JSON(http.StatusNotFound, gin.H{"detail": "Team not found"})
				return
			}
			deps, err := services.GetTeamProjectDependencies(database.DB, teamID, projectID)
			if err != nil {
				c.JSON(http.StatusInternalServerError, gin.H{"detail": err.Error()})
				return
			}
			c.JSON(http.StatusOK, deps)
		})
	}

	// MVP 阶段不提供手动管理依赖的写端点。
	// 依赖关系由 Swagger / OpenAPI / Postman 导入流程自动生成。
	d405 := func(c *gin.Context) {
		c.JSON(http.StatusMethodNotAllowed, gin.H{
			"detail": "Dependency relationships are read-only in MVP. They are auto-generated by Swagger / OpenAPI / Postman import.",
		})
	}
	r.POST("/teams/:team_id/projects/:project_id/dependencies", d405)
	r.PUT("/teams/:team_id/projects/:project_id/dependencies/:id", d405)
	r.PATCH("/teams/:team_id/projects/:project_id/dependencies/:id", d405)
	r.DELETE("/teams/:team_id/projects/:project_id/dependencies/:id", d405)
}

